name: github pages

# mainブランチにプッシュしたときjobsに記述した操作を行う
on:
  push:
    branches:
    - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-deploy:
    # ubuntu OS を仮想マシン上に用意する
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # python環境のセットアップを行う
      - name: setup python3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      # スクリプト実行
      - name: build
        run: python3 ./builder.py

      - name: Check git repos
        uses: actions/checkout@v3
      # 差分があるか調べる
      - name: Diff
        id: diff
        run: |
          git add -N .
          git diff --name-only --exit-code
        continue-on-error: true
      # 結果をコミットする
      - name: commit
        run: |
          git config user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          git add .
          git commit -m "Auto generate"
          git push
        if: steps.diff.outcome == 'failure'

      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: './out'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
